# trustPolicy: no-downgrade

packages:
  - 'packages/*'
  - '!packages/create-admin/template'
  - playground
  - docs
catalog:
  '@antdv-next/auto-import-resolver': ^1.0.7
  vite: ^6.4.2
catalogMode: prefer

# overrides:
#   undici-types: 6.20.0
#   vitepress>vite: 7.3.1

onlyBuiltDependencies:
  - core-js
  - esbuild
  - simple-git-hooks
  - typescript
  - vite
  - vitest
  - vue
  - vue-tsc
shellEmulator: true
