name: Setup CI

runs:
  using: composite
  steps:
    - name: Using pnpm
      uses: pnpm/action-setup@v3
      with:
        version: latest

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: current
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install
