name: Setup CI

runs:
  using: composite
  steps:
    - name: Using pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9.15.4

    - name: Setup Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install
