name: Setup CI

runs:
  using: composite
  steps:
    - name: Using pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9.3.0

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm

    - name: Install dependencies
      run: pnpm install