name: Setup CI
description: Install pnpm, Node.js and workspace dependencies

runs:
  using: composite
  steps:
    - name: Using pnpm
      uses: pnpm/action-setup@v6.1.0
      with:
        version: 12.8.1

    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version: 24.21.0
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install
