export const PATH_DASHBOARD = '/dashboard'
export const PATH_LOGIN = '/login'
export const PATH_ERROR = '/error/:code'
export const PATH_NOT_FOUND = '/error/404'
export const PATH_PERMISSION_DENY = '/error/403'
