export enum FormType {
  Input = 'input',
  Password = 'password',
  InputNumber = 'inputNumber',
  Date = 'date',
  DateTime = 'datetime',
  Year = 'year',
  Month = 'month',
  Week = 'week',
  Time = 'time',
  Radio = 'radio',
  Checkbox = 'checkbox',
  Switch = 'switch',
  Rate = 'rate',
  Slider = 'slider',
  Upload = 'upload',
  Cascader = 'cascader',
  Transfer = 'transfer',
  DateRange = 'dateRange',
  DateTimeRange = 'datetimeRange',
  YearRange = 'yearRange',
  MonthRange = 'monthRange',
  WeekRange = 'weekRange',
  TimeRange = 'timeRange',
  Select = 'select',
  Selector = 'selector',
}
